# Generated by Django 4.1.6 on 2024-05-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_message_read_at_remove_message_replied_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
