# Generated by Django 4.1.6 on 2024-05-30 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartman',
            name='location',
            field=models.CharField(default='Nedefinirano', max_length=200),
        ),
        migrations.AddField(
            model_name='apartman',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('apartman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.apartman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
