# Generated by Django 4.1.6 on 2024-05-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_apartman_location_apartman_price_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartman',
            name='apartman_image',
            field=models.ImageField(blank=True, null=True, upload_to='apartman_images/'),
        ),
        migrations.AlterField(
            model_name='apartman',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apartman',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
