# Generated by Django 4.1.6 on 2024-05-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_apartman_apartman_image_alter_apartman_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartman',
            name='location',
        ),
        migrations.RemoveField(
            model_name='apartman',
            name='price',
        ),
        migrations.AlterField(
            model_name='apartman',
            name='apartman_image',
            field=models.ImageField(blank=True, null=True, upload_to='apartman_img/'),
        ),
    ]
