# Generated by Django 4.1.6 on 2024-05-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_apartman_location_remove_apartman_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
