# Generated by Django 4.1.6 on 2024-06-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartman',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='apartman',
            name='location',
            field=models.TextField(default='no location'),
        ),
        migrations.AddField(
            model_name='apartman',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
