# Generated by Django 4.1.6 on 2024-06-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_apartman_contact_number_apartman_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartman',
            name='apartman_image',
        ),
    ]
